### ISSUE TITLE
cargo build with openssl and grpcio will report error: undefined reference to `OPENSSL_add_all_algorithms_noconf'

### ISSUE THREAD

**Issue by dllhlx** [pingcap/grpc-rs#105]
My Cargo.toml as below:
```
[dependencies]
openssl = "0.9.20"
grpcio = "0.1"
```
run ```cargo build``` will report error: 
```
note: /home/test/target/debug/deps/libopenssl_sys-83f37b3f53691d0c.rlib(openssl_sys-83f37b3f53691d0c.0.o): In function `openssl_sys::ossl10x::init::{{closure}}':
          /home/test/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.20/src/o  l10x.rs:768: undefined reference to `OPENSSL_add_all_algorithms_noconf'
▽         collect2: error: ld returned 1 exit status
```
if I remove grpcio from Cargo.toml dependencies then cargo build will be ok. Anybody meet this case?

**Comment by siddontang** [comment]
PTAL @BusyJay

**Comment by dllhlx** [comment]
```grpcio links BoringSSL, which is incompatible with OpenSSL. ``` Is This conclusion correct ?

**Comment by dllhlx** [comment]
@siddontang @BusyJay

**Comment by BusyJay** [comment]
Yes. If you want to link to openssl instead, you can build grpc library by yourself. And then link to it by setting environment variable `GRPCIO_SYS_USE_PKG_CONFIG=1`. Then `pkg-config` is used to get the required linking information.

**Comment by dllhlx** [comment]
@BusyJay  thx a lot.
