### ISSUE TITLE
Can grpcio support host or ip whitelist

### ISSUE THREAD

**Issue by dllhlx** [pingcap/grpc-rs#106]
As desc as title, can grpcio support host or ip whitelist function to filter out some request.

**Comment by dllhlx** [comment]
Or is there any function to obtain remote client ip from server meta data?

**Comment by BusyJay** [comment]
You can obtain the address of remote endpoint via `grpc_call_get_peer` ABI, though it's not used in this crate yet. It will be appreciated if you can help us to add such an API.

**Comment by dllhlx** [comment]
@BusyJay  get it, thx!

**Comment by dllhlx** [comment]
@BusyJay  I try add a pub fn in ```Struct RpcContext```, the func is
```
pub fn get_peer(&mut self) -> String{
        unsafe {
            let call = grpc_sys::grpcwrap_request_call_context_take_call(self.ctx);
            if call.is_null() {
                return "NIL".to_string(); <------ exit as the call is null
            }
            let peer = grpc_sys::grpc_call_get_peer(call);
            let peer = CString::from_raw(peer);
            peer.to_str().unwrap().to_owned().to_string()
        }
    }
```
but this func always exit as the call is null, so the grpc_call_get_peer will never be called .

**Comment by BusyJay** [comment]
That's because the call is taken before `peer` method is called. You can fetch it early in the construction of `RpcContext`.

**Comment by dllhlx** [comment]
@BusyJay  I already finish this func succ,  thx very much!

**Comment by dllhlx** [comment]
update grps-rs code can get peer info, so this issue can be closed.

**Comment by BusyJay** [comment]
Good for you! And it would be very appreciated if you can raise a PR for your changes.
