### ISSUE TITLE
Tests and benchmarks failed after upgrade gRPC to 1.7.2

### ISSUE THREAD

**Issue by overvenus** [pingcap/grpc-rs#118]
As described in https://github.com/pingcap/grpc-rs/pull/113#issuecomment-344896176, benchmarks failed. 
And unit tests fail frequently because of `call.c:2032] assertion failed: grpc_cq_begin_op(call->cq, notify_tag)`

For the benchmark, it looks like client and server failed to send the last message and close the connection, detailed logs:

Client:
```
Nov 18 14:34:27.584 INFO listening on [::]:10110
Nov 18 14:34:27.703 INFO receive client setup: server_targets: "localhost:33821" client_type: ASYNC_CLIENT security_params {use_test_ca: true server_host_override: "foo.test.google.fr"} outstanding_rpcs_per_channel: 100 client_channels: 64 rpc_type: STREAMING load_params {closed_loop {}} payload_config {simple_params {}} histogram_params {resolution: 0.01 max_possible: 60000000000} channel_args {name: "grpc.optimization_target" str_value: "throughput"}
Nov 18 14:34:27.859 INFO receive client mark: reset: true
Nov 18 14:34:32.864 INFO receive client mark: reset: true
Nov 18 14:35:02.862 INFO receive client mark: reset: true
```
 
Server:
```
Nov 18 14:34:27.581 INFO listening on [::]:10100
Nov 18 14:34:27.594 INFO receive server setup: server_type: ASYNC_SERVER security_params {use_test_ca: true server_host_override: "foo.test.google.fr"} channel_args {name: "grpc.optimization_target" str_value: "throughput"}
Nov 18 14:34:32.865 INFO receive server mark: reset: true
```

They are both missing a log for shutting down.
https://github.com/pingcap/grpc-rs/blob/e45a84332e7e8c5e490ade91a501610f612fdce8/benchmark/src/worker.rs#L113
https://github.com/pingcap/grpc-rs/blob/e45a84332e7e8c5e490ade91a501610f612fdce8/benchmark/src/worker.rs#L77

CC #107

**Comment by BusyJay** [comment]
This is because `grpc_call_start_batch` is called after the completion queue is shutdown. We need to check it every time completion queue is access.
