### ISSUE TITLE
Is there a interface to support diffie-hellman algorithm?

### ISSUE THREAD

**Issue by dllhlx** [pingcap/grpc-rs#121]
As the stream is not safe in grpc insecure channel, is there a interface that I can use diffie-hellman algorithm in transfer progress?

**Comment by BusyJay** [comment]
Why not just use secure channel?

**Comment by dllhlx** [comment]
@BusyJay  In my application model,  I can't use the secure channel.  I can only use insecure channel but the stream is not safe, so if there is a interface support diffie-hellman  in grpcio i can use to encrypt the data.

**Comment by siddontang** [comment]
@dllhlx, does core C gRPC support this? If yes, you can help us to add this feature.

**Comment by dllhlx** [comment]
@BusyJay  @siddontang  can add DH algorithm in file ```src/codec.rs``` the pb_codec section like
```
pub mod pb_codec {
    use protobuf::{self, Message, MessageStatic};

    use error::Result;

    #[inline]
    pub fn ser<T: Message>(t: &T, buf: &mut Vec<u8>) {
        //add DH logic here <-------------
        t.write_to_vec(buf).unwrap()
    }

    #[inline]
    pub fn de<T: MessageStatic>(buf: &[u8]) -> Result<T> {
        //add DH logic here <-------------
        protobuf::parse_from_bytes(buf).map_err(From::from)
    }
}
```

**Comment by siddontang** [comment]
We design to support different codec protocols, maybe it can work.

/cc @BusyJay

**Comment by dllhlx** [comment]
@siddontang  I try this solution, ant it works!

**Comment by siddontang** [comment]
Cool
