### ISSUE TITLE
Bad codegen 

### ISSUE THREAD

**Issue by m4b** [pingcap/grpc-rs#142]
I’m seeing bad codegen with protoc version 3.0.0 and latest rust grpc plugin. 

Specifically proto grpc api generated passes the request by reference but unary_call requires it by value. 

Similarly iter_opt method returns a result but codegen doesn’t wrap in Ok.

Consequently have to fix this by hand...

**Comment by BusyJay** [comment]
You need to use latest grpcio crate to work with the coded generated by latest rust gRPC plugin. Maybe we need to add some compile time check to provide more friendly and clear error message.

**Comment by m4b** [comment]
Could you clarify this exactly, specifically which versions or do you mean git ?

I used the latest plugin with the latest grpcio both from crates.io and I had this issue

**Comment by BusyJay** [comment]
grpcio v0.2.0 should work with grpcio-compiler v0.2.0. Can you provide the proto files that can cause the problem?

**Comment by m4b** [comment]
Omg I’m sorry, somehow I was on 0.1 and didn’t notice :/ sorry about this, and thanks for the follow up clarification, 0.2 works as expected with 0.2 tool

So I think what happened is I followed the readme which states to use the 0.1 grpcio but cargo install for grpcio-compiler will install latest on crates.io

Might be a good idea to update readme to use 0.2

And thanks for this, works really well!
