### ISSUE TITLE
grpcio-sys requires go?

### ISSUE THREAD

**Issue by m4b** [pingcap/grpc-rs#149]
On two separate systems, compilation of sys fails when go is not installed.

The readme does not seem to indicate this is a requirement, am I doing something wrong here?

I would really prefer not to have go installed for compilation on my dev machine, is it possible?

**Comment by BusyJay** [comment]
Actually README says it in prerequisites.

> If you want to enable secure feature, Go (>=1.7) is required.

gRPC core depends on boringssl, which uses go to generate some data sets.

**Comment by m4b** [comment]
Yea, the way I read that is its optional, _if_ you want the secure feature, then go is required; otherwise not.

If it isn't configurable then it seems more accurate to just write Go >= 1.7 is required in the dependencies, since it isn't buildable otherwise.

**Comment by BusyJay** [comment]
It's indeed optional. Maybe some dependency enable the secure features for grpcio-sys? If you happen to use grpcio-proto, then secure features is enabled by it.

**Comment by m4b** [comment]
I’m pretty sure I use grpcio proto, will check. Assuming I do, is there anyway to turn off secure features there so the go dependency isn’t needed ?

Also, while I’m at it, where is the secure feature documented? I should just read what it does before trying to turn it off probably ;)

**Comment by BusyJay** [comment]
TLS is not supported until secure features is enabled. You are welcome to send a PR to refactor grpcio-proto to separate secure features from the default features.

**Comment by ondj** [comment]
This can be closed, because https://github.com/pingcap/grpc-rs/pull/199 was merged
