### ISSUE TITLE
streaming call is not canceled when channel is dropped

### ISSUE THREAD

**Issue by BusyJay** [pingcap/grpc-rs#150]
We observe that in some case streaming call won't be canceled automatically when underlying channel is dropped. It can be reproduced reliably with TiKV, though a simple ping pong example can't reproduced it yet.

**Comment by siddontang** [comment]
> a simple ping pong example can't reproduced it yet

Does it use a Unary API? Maybe we should use a BiDirectional API?

**Comment by BusyJay** [comment]
No, it's a duplex streaming call.
