### ISSUE TITLE
Setting max message len seems to have no affect

### ISSUE THREAD

**Issue by m4b** [pingcap/grpc-rs#153]
Using channel builder, if I set max message len and max receive len to usize max, for example, it does not appear to be respected and the default of 4MB limit is hit for messages larger than 4MB

Looking at the source everything seems to be in order, the options are iterated and set, etc.

Nevertheless I still cannot seem to increase the max message size

**Comment by BusyJay** [comment]
Hi, could you show us how did you set the size limit? TiKV also [use these settings](https://github.com/pingcap/tikv/blob/63eb6fabc274dee82dce3e6effe6bb288ebeb748/src/server/raft_client.rs#L60) and they works just fine.

**Comment by m4b** [comment]
I do exactly what you do. I’ll try to make a minimal repro.

But have you verified you can create a 5Mb message with your settings ? You set them to 10MB but perhaps your messages are never over the 4MB limit in which case you wouldn’t see it

**Comment by m4b** [comment]
I’ve just verified that I can decrease the amount, say to 1024, and it reports this value on the grpc error, but I cannot increase it past 4MB

**Comment by m4b** [comment]
Actually sorry, I cannot decrease max read either; only max send.  I believe max send value is correctly modified, since I’m definitely sending large messages over 4MB but the max receive won’t take them. 

It seems max send is recognized but max read seems to be completely ignored.

**Comment by BusyJay** [comment]
We have test cases covering it. :)

Please also make sure you modify the size limit on the server side too, just as [we do](https://github.com/pingcap/tikv/blob/63eb6fabc274dee82dce3e6effe6bb288ebeb748/src/server/server.rs#L102).

**Comment by m4b** [comment]
Arghhhhhhhhh didn’t even occur to me that would be required on server too, but of course. 

Thanks for the pointer! Works as expected, closing this :)
