### ISSUE TITLE
Can this be made to work with prost somehow?

### ISSUE THREAD

**Issue by SirVer** [pingcap/grpc-rs#155]
`rust-protobuf` gives me headaches with our complex repo with many protos all over the place. However, since I require gRPC, I am using it still instead of `prost` which seems easier to work with. 

Can this repo be made to work with `prost` somehow?

**Comment by siddontang** [comment]
Seem we can support different codec algorithm, and maybe can work now.
/cc @BusyJay

**Comment by BusyJay** [comment]
Yes. `grpcio` is designed to work with different serialization/deserialization implementations/frameworks, just as grpc protocol itself. To support `prost`, you need to implement a custom grpcio compiler which generates code that adapt to `prost`. There are two key adaptations:

1. Implement marshallers for `prost`, you can see the implementation for rust-protobuf [here](https://github.com/pingcap/grpc-rs/blob/4ab833247f3e41da103a699e3bc2579a71adeaa1/src/codec.rs#L36);
2. Construct method using the customized marshallers in the generated code, for example
```
const METHOD_EXAMPLE: ::grpcio::Method<pb::Request, pb::Response> = ::grpcio::Method {
    ty: ::grpcio::MethodType::Unary,
    name: "/pbname.service/method",
    req_mar: ::grpcio::Marshaller { ser: custom_ser, de: custom_de },
    resp_mar: ::grpcio::Marshaller { ser: custom_ser, de: custom_de },
};
```

Also, you may want to disable the default features of grpcio, which will enable protobuf-codec automatically.

**Comment by SirVer** [comment]
That seems pretty straightforward. Thank you!
