### ISSUE TITLE
Linking fails: /usr/lib/libssl.so.1.1: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by domohawk** [pingcap/grpc-rs#164]
A clean project with:
```
[dependencies]
grpcio-proto = "0.2.0"
oauth2 = "1.3.0"
```
and main.rs:
```
extern crate oauth2;
fn main() {
  oauth2::Config::new("", "", "","").authorize_url();
}
```

Will fail linking with:
> error: linking with `cc` failed: exit code: 1
>   |
> = note: /usr/bin/ld: /home/user/git/project/target/debug/deps/libopenssl_sys-595a0ddae1d3fd8b.rlib(openssl_sys-595a0ddae1d3fd8b.openssl_sys2.rcgu.o): undefined reference to symbol 'SSL_ctrl@@OPENSSL_1_1_0'
>           /usr/lib/libssl.so.1.1: error adding symbols: DSO missing from command line
>           collect2: error: ld returned 1 exit status

I do have the libssl.so, it contains the symbol, and -l ssl appears on the linker line. I've also tried moving the -l's around but no change.

Oddly enough if I comment out either the "authorize_url" line or the grpcio-proto dep, it works. A grpcio dep with features = ["secure"] will also repro. I kind of suspect its not oauth2 since it doesn't have any linker-generated code like grpc-rs.

Any clue to solving this? The only similar issue I found was [this one](https://github.com/rust-qt/cpp_to_rust/commit/28f499051841a36d0aad877e90c9a2f6cfdf7e08) resulting from a bad link ordering. My gut tells me it might be somewhere around [grpcio-sys/build.rs](https://github.com/pingcap/grpc-rs/blob/master/grpc-sys/build.rs#L120) but I am just learning Rust and kind of at a dead end.

**Comment by siddontang** [comment]
PTAL @BusyJay

**Comment by BusyJay** [comment]
That's because grpc-sys use embed boringssl instead of openssl by default. So the `-l ssl` will link to the ssl library shipped with this crate, which doesn't contains the `SSL_ctrl` symbol.
If you want to link to openssl instead, you can [build grpc core library](https://github.com/pingcap/grpc/blob/rs-release/INSTALL.md) by yourself. And then link to it by setting environment variable GRPCIO_SYS_USE_PKG_CONFIG=1. Then `pkg-config` is used to get the required linking information.

**Comment by domohawk** [comment]
Thanks for the quick reply!

Would this happen any time then a crate depended both on grpcio and another crate with a transitive dependency on openssl? Is there a way to add a guard to the grpcio crate to warn/error with a friendly message?

Also, why does grpcio-proto need ssl if grpcio (without secure) does not?

**Comment by BusyJay** [comment]
> Would this happen...

Yes.

> Is there a way to add a guard to the grpcio crate to warn/error with a friendly message?

AFAIK, I don't think a crate can tell exactly if another crate is involved at compile time.

> ...  why does grpcio-proto need ssl...

Because grpcio-proto includes some useful functions for writing interop tests which needs secure features. Although I believe they can be compiled conditionally.

**Comment by domohawk** [comment]
So building pingcap/grpc was straightforward, and happy to be onward with my project, but as a Rust newbie I am curious to ask:

What is the downside to not embed an ssl impl (or other link requirements) in the crate, and by default use the one on the system? Would that not be more portable?

**Comment by BusyJay** [comment]
We enable it by default to make things simple, so that users can simply run `cargo build` and get things done. Otherwise user is required to install openssl-devel or any package similar to move forward. And using a built-in one can also make binary/tests more deterministic.

**Comment by domohawk** [comment]
I see, I guess I don't really have enough experience with Rust or this type of build system. I'm used to fetching all needed C++ sources to build aside from standard system libs.

Thanks for your help!
