### ISSUE TITLE
whether this project supports cross-compiling in windows or not?

### ISSUE THREAD

**Issue by dllhlx** [pingcap/grpc-rs#168]
As desc in title, whether this project supports cross-compiling in windows or not?

**Comment by BusyJay** [comment]
The project is neither tested with nor do anything particularly for cross-compiling. Did you meet any error during compilation?

**Comment by light4** [comment]
参考 #169 。可以交叉编译 grpc-rs。
为了支持交叉编译，build.rs 需要使用 `CARGO_CFG_TARGET_OS` `CARGO_CFG_TARGET_ARCH` 等 CARGO 参数，来判断具体的 target。

**Comment by dllhlx** [comment]
@BusyJay  thanks, I have fix it.

**Comment by dllhlx** [comment]
@light4  thanks.
