### ISSUE TITLE
Use actual gRPC library

### ISSUE THREAD

**Issue by JakubOnderka** [pingcap/grpc-rs#197]
Hi,

today was released v1.13.0 of gRPC Core library. But this crate currently uses v1.6.1 from 15. September 2017. There was tries to update library to version 1.8 (#139) or 1.10.0 (#171), but to today are not merged. 

Is there any plan to update the underlining library? Do you need help with something?

**Comment by overvenus** [comment]
Hi @JakubOnderka

We are going to upgrade gRPC Core in early July, probably still 1.10.x(#171).
The main blocker for #171 is 1.10.0 removes `struct grpc_alarm` in
grpc/proposal#53 and grpc/grpc#14015. grpc-rs needs alarm to notify
gRPC's `CompletionQueue` that there is a `Future` is `Ready` to poll.

I add it back in pingcap/grpc#11, [`6471103`](https://github.com/pingcap/grpc/pull/11/commits/6471103e25a936669746ed7d79b6da464fc77417), but that makes grpc-rs incompatible
with the official gRPC Core library. Users have to build grpc-rs staticlly
or install pingcap/gRPC. ☹️

**Comment by JakubOnderka** [comment]
I understand that maintain fork is very hard. But according to https://github.com/grpc/grpc/pull/14015, they implemented that functionality in C++ layer, so it is not possible to reimplement it in Rust or use C++ implementation next to original C gRPC lib?

**Comment by overvenus** [comment]
FYI, grpc++ alarm wrapper is working in progress, I am not familiar with c++, so it may take me few days.

If grpc++ alarm works well, we can still have the nice link feature, `GRPCIO_SYS_USE_PKG_CONFIG`.

https://github.com/pingcap/grpc-rs/blob/ae0130db0e3fe430e7526be37dc67358a22b2f65/grpc-sys/build.rs#L154

**Comment by ice1000** [comment]
Is #203 closing this issue?

**Comment by ice1000** [comment]
@overvenus PTAL

**Comment by ice1000** [comment]
Closing
