### ISSUE TITLE
How do make client wait before the server is connectable?

### ISSUE THREAD

**Issue by abbychau** [pingcap/grpc-rs#198]
as title, and also, how to implement reconnection?

**Comment by BusyJay** [comment]
Channel handles the backoff and reconnects automatically, you can see the explanation [here](https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md#grpc-connectivity-semantics-and-api).

**Comment by BusyJay** [comment]
Closing this. If you have further questions, feel free to reopen it or create a new issue.

**Comment by abbychau** [comment]
do you have a sample using grpc-rs to wait until the server is connectable?
