### ISSUE TITLE
grpcio-sys and vendored SSL fails to link on Linux

### ISSUE THREAD

**Issue by chefsalim** [pingcap/grpc-rs#214]
I'm running into the exact issue that is documented in this thread - https://users.rust-lang.org/t/linking-to-openssl-fails-but-only-on-linux/13199/3

Linking fails on Linux when grpc is added to an existing project that also includes other openssl dependencies.  The system openssl is 1.1.0g

Example error:
openssl_sys-0ef71b21e0664078.openssl_sys2.rcgu.o): undefined reference to symbol 'SSL_CTX_callback_ctrl@@OPENSSL_1.0.0'
          //lib/x86_64-linux-gnu/libssl.so.1.0.0: error adding symbols: DSO missing from command line

Any workaround would be appreciated!

**Comment by BusyJay** [comment]
There is a pr (#186) which tries to make peace between openssl and grpc, but it's not merged yet. For now you can try the solution mentioned in #105.

**Comment by ice1000** [comment]
@chefsalim Will close this issue after 1 day without reply.
