### ISSUE TITLE
Support configure thread number per completion queue?

### ISSUE THREAD

**Issue by qiuxiafei** [pingcap/grpc-rs#219]
Currently threads on a completion queue is fix to 1.

**Comment by Hoverbear** [comment]
:laughing: I'm not sure if this is a bug. @BusyJay , what do you think?

**Comment by BusyJay** [comment]
No, it's intended. For the reason in #148 and avoiding potential context switches.

**Comment by Hoverbear** [comment]
Thanks @BusyJay ! I'll close this since it's not an issue.
