### ISSUE TITLE
TiKV paniced if using the latest master, with zero-copy feature.

### ISSUE THREAD

**Issue by hicqu** [pingcap/grpc-rs#244]
I tested tikv with latest master grpc-rs, by specifying this in `Cargo.toml`:
```toml
[replace]
"grpcio:0.4.0" = { git = "https://github.com/pingcap/grpc-rs.git" }
```
But tikv paniced later. From the log the error happens in something about `grpc_slice`.
Please take a look. The log is attached.
[tikv.log](https://github.com/pingcap/grpc-rs/files/2500053/tikv.log)

**Comment by ice1000** [comment]
What's the relationship between this issue and #245 ?

**Comment by overvenus** [comment]
They are the issue. I submitted #245 because I did not see this one due to github october21-incident.
