### ISSUE TITLE
Support "wait for ready" semantics

### ISSUE THREAD

**Issue by ice1000** [pingcap/grpc-rs#261]
Related doc: https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md
This is a special feature provided by grpc.

**Comment by abbychau** [comment]
isn't it already an existing flag in grpc-rs?
https://docs.rs/grpcio/0.4.1/grpcio/struct.CallOption.html#method.wait_for_ready

do you mean that it is not implemented?

**Comment by ice1000** [comment]
O
Then this issue might be a false positive.
