### ISSUE TITLE
Code that does client-server

### ISSUE THREAD

**Issue by MathieuDutSik** [pingcap/grpc-rs#290]
I would like code that does both server work (by processing request) and server work (by contacting other servers). 
Is it at all possible with grpc library?
The examples given are either client or server and this leaves open whether one can use grpc for this purpose. If possible, a non-trivial example would be much welcomed.

**Comment by BusyJay** [comment]
Yes, the library works for both client and server. TiKV uses the library for both client and server usage. And interop unit tests do the similar things too.
