### ISSUE TITLE
In process client server optimizations?

### ISSUE THREAD

**Issue by jessegrosjean** [pingcap/grpc-rs#293]
I'm building an app with Rust for model layer and Swift for the UI.

I'm using `grace-rs` and `grpc-swift` to structure the communication between the layers. It's working pretty well, but I'm wondering if I can optimize the communication since both the client and server are running in the same process.

In particular I'm wondering if I can make the communication skip the network stack and just use in process communication. I think both `grace-rs` and `grpc-swift` are built on `gRPC C`. And I "think" that supports "In Process" transport as [shown here](https://grpc.io/blog/grpc-stacks).

But I haven't noticed any documentation on how I might turn on in process transport? Is this a possibility now? Or might it be in the future?

**Comment by BusyJay** [comment]
I don't think it's possible. You always need an address to start a service and send requests to it, which means a socket is required. But if they are in one process, you can use local loopback addresses. OS usually has special optimization for such addresses.

**Comment by jessegrosjean** [comment]
Ok, thanks.

**Comment by cameron-martin** [comment]
@BusyJay can you elaborate on why this isn't possible? Is this a limitation of the gRPC C++ library or the bindings? The docs (as posted above and [here](https://grpc.github.io/grpc/core/md_doc_core_transport_explainer.html)) would suggest this is possible from the gRPC point of view, although from looking at the gRPC source it doesn't seem clear to me how to switch out these transports.

**Comment by BusyJay** [comment]
Interesting. It seems possible from provided code. Although it's not a public C API. But I think it's possible to expose it if we use bundle grpc.
