### ISSUE TITLE
Server to client dynamic streaming best practices

### ISSUE THREAD

**Issue by jessegrosjean** [pingcap/grpc-rs#295]
The current server to client streaming example that I can find `RouteGuide::list_features` works by first gathering all the features that it wants to return, and then using `send_all` to stream them to the client.

I'm interested in an example that will instead setup a stream, and then save a send handle on the server. And periodically use that handle to send events to the client. So in this case all the events that will be streamed are not known at the time that the client requests the stream. I'm wondering what the best way to do this is.

Here's my try, I'd like to know how it can be improved:

```rust
use futures::prelude::*;
use futures::sync::mpsc::*;
use grpcio::{RpcContext, ServerStreamingSink, WriteFlags};
use log::{error, info};
use std::thread;

use crate::proto::workspace::{Event, StreamEventsRequest};
use crate::proto::workspace_grpc;

#[derive(Clone)]
pub struct EventsService {}

impl workspace_grpc::EventsService for EventsService {
  fn stream_events(
    &mut self,
    ctx: RpcContext,
    _req: StreamEventsRequest,
    sink: ServerStreamingSink<Event>,
  ) {

    // 1. Create a channel
    let (sender, receiver) = channel(10);

    // 2. Forward channel receiver events to sink to client
    ctx.spawn(
      receiver
        .map(|e| (e, WriteFlags::default()))
        .forward(sink.sink_map_err(|e| error!("sink error: {:?}", e)))
        .map(|_| ())
    );

    // 3. Start a server process to send events for a while. The thread is used
    //    to simulate what I really want to do: Save the `Sender` in the
    //    `EventsService` struct, and when an event happens on the server use
    //    that sender to notifiy the client.
    thread::spawn(move || {
      for i in 0..3 {
        let mut event = Event::new();
        event.set_name(format!("{}", i));
        thread::sleep(::std::time::Duration::from_millis(1000));
        if sender.clone().send(event).wait().is_err() {
          return
        }
      }
    });
  }
}
```

I'm particularly interested in step (3) in the above code. Right now to send I need to both clone the sender and wait on result each time. Is this the best way to be doing things?

- Do I really need/want clone the sender for each send?
- Is there a way that I can send without needing to block? Some way to get a handle on a `RpcContext` from outside the context of a request handler?
- Do I need to be calling `close` on the `ServerStreamingSink` in the above code, or is that happening automatically for me somehow?

**Comment by jessegrosjean** [comment]
I think my key question is:

> Is there a way that I can send without needing to block when I don't have immediate access to a `RpcContext`?

In most examples of `grpcio` the `RpcContext` is used to spawn futures. But if I create a future in a separate thread (above example) then I don't have access to `RpcContext`. In that case what is the best way to drive the future.

I know that one way that I can do it is by blocking (calling `wait()`) on the future. But I wonder if it would be better to instead use `grpcio's` internals (I think it comes down to the `CompletionQueue` in the end) drive that future. Is there a way to do this?

**Comment by BusyJay** [comment]
> Do I really need/want clone the sender for each send?

No, you don't have to. `Sender::send` returns a future, which can be resolved to sender itself. You can use it instead of clone another one.

> Is there a way that I can send without needing to block?

Yes. `wait` should not be called. You can use some executors that can drive futures like future-cpupool or threadpool.

> Some way to get a handle on a RpcContext from outside the context of a request handler?

No, `RpcContext` only valids inside the method, and it will be freed after that.

> Do I need to be calling close on the ServerStreamingSink in the above code, or is that happening automatically for me somehow?

 `forward` will call `send_all` under the hook, which will close the stream and sink. And you are recommended to call close method if not use those methods, otherwise the remote may wait for the call till timeout.

> instead use grpcio's internals...

It's not a good idea to use CompletionQueue to drive all the futures. In practice, you probably want to separate the IO workload with computation workload. You can use channel to bridge them and use suitable executors to drive the send end, such as tokio-reactor, threadpool and so on.

**Comment by jessegrosjean** [comment]
Thanks for your help.
