### ISSUE TITLE
Unexpected `drop` of instance during server rpc creation

### ISSUE THREAD

**Issue by abbychau** [pingcap/grpc-rs#304]
**Describe the bug**
By looking into https://github.com/pingcap/grpc-rs/blob/master/compiler/src/codegen.rs#L491 or
https://github.com/pingcap/grpc-rs/blob/master/compiler/src/prost_codegen.rs#L473

Resources of the server are passing into the method and being dropped afterwards, because the resource (`s`) is not moving into any of the handlers and was dropped afterwards.

E.g.
```Rust
pub fn create_account_info_rpc<S: AccountInfoRpc + Send + Clone + 'static>(s: S) -> ::grpcio::Service {
    let mut builder = ::grpcio::ServiceBuilder::new();
    let mut instance = s.clone();
    builder = builder.add_unary_handler(&METHOD_ACCOUNT_INFO_RPC_CLIENT_ACCOUNT_INFO, move |ctx, req, resp| {
        instance.client_account_info(ctx, req, resp)
    });
    let mut instance = s.clone();
    builder = builder.add_unary_handler(&METHOD_ACCOUNT_INFO_RPC_ADD_CLIENT_ACCOUNT_INFO, move |ctx, req, resp| {
        instance.add_client_account_info(ctx, req, resp)
    });
    let mut instance = s.clone(); //cloning s
    builder = builder.add_unary_handler(&METHOD_ACCOUNT_INFO_RPC_UPDATE_CLIENT_ACCOUNT_INFO, move |ctx, req, resp| {
        instance.update_client_account_info(ctx, req, resp)
    });
    builder.build() //s dies here
}
```
The last cloning is obviously not needed and it may potentially trigger `drop` trait of struct of `s`.

It is better to change the last `let mut instance = s.clone();`.

**Comment by siddontang** [comment]
PTAL @BusyJay
