### ISSUE TITLE
general use or tikv only?

### ISSUE THREAD

**Issue by biolee** [pingcap/grpc-rs#31]
is there any readme or else? this is build for tikv only or a general grpc implimentation in rust?

**Comment by ngaut** [comment]
It's a general gRPC wrapper that wrap the origin c-implementation. Not just for TiKV. And it will be used in go client and jave client to communicate with tikv server.

**Comment by BusyJay** [comment]
I think go client and java client will use their specific grpc implementations (grpc-go/grpc-java) instead. But the wrapper will be compatible with them for sure.
