### ISSUE TITLE
separate grpc-rs-example for easy reuse by others

### ISSUE THREAD

**Issue by omac777** [pingcap/grpc-rs#319]
**Is your feature request related to a problem? Please describe.**
I can build grpc-rs successfully.
I understand the .proto files.
I understand the examples.

My painpoint is separating the grpc-rs crate from the examples and proto in order to create a standalone example and customized version of the example only within my own standalone local crate with "cargo new".

**Describe the solution you'd like**
Could you please create a separate example that grpc-rs users can "git clone"
I.e. git clone https://github.com/pingcap/grpc-rs-example
from which we can simply rename locally then customize & build from.

**Describe alternatives you've considered**
I totally appreciate the proto/build.rs building from .proto file and outputting the .desc file for the examples.  Having a separate example would help a great deal for others to reuse grpc-rs.

Thank you for listening.

**Additional context**

**Comment by ice1000** [comment]
The current `examples` directory is not intended to be "reused".
They're configured in the project root Cargo.toml, as **parts of this crate**, which means they cannot simply be extracted elsewhere.

Plus, the `examples` directory is not one example. It's four examples. Are you requesting for four standalone repositories to be created?
https://github.com/pingcap/grpc-rs/blob/737d9229c701cc382d9a0fd3209ff739d1b5ea9f/Cargo.toml#L39-L53

**Comment by ice1000** [comment]
Personally I'll recommend you to start from your own project and then integrate grpc-rs, instead of starting from a library example.

**Comment by ice1000** [comment]
No reply, closing. For similar questions, please create new issues.
