### ISSUE TITLE
Use bindgen to generate C bindings automatically

### ISSUE THREAD

**Issue by hunterlxt** [pingcap/grpc-rs#331]
**Is your feature request related to a problem? Please describe.**
We used to implement the bindings to C by handwriting, but the upstream repo is changing at any time. As the rust-language and bindgen matures, we are considering the way to generate bindings using bindgen.

**Describe the solution you'd like**
1. Maintain a file like `filter.h` to contain all header files with `GPRAPI` and `GRPCAPI`. （Avoid irrelevant header files, if those header files are really needed, the relevant header files will definitely include them.） Note: The `filter.h` is not mandatory. I don't know if it is better to retrieve those headers directly from the `include/grpc/` in `build.rs`.
2. Only function bindings prefixed with `gpr_` and `grpc_` are generated by a whitelist-like approach

**Possible problems**
1. Code using the grpc-sys library may need to be updated.
2. Some of Bindgen's undiscovered bugs may affect our code, and automatically generated code needs to be reviewed.

**Comment by hunterlxt** [comment]
@BusyJay Pls take a look

**Comment by BusyJay** [comment]
I prefer specifying the headers in build.rs if it's possible.

> Code using the grpc-sys library may need to be updated.

We can release a new version for the changes.

> Some of Bindgen's undiscovered bugs

I think it's OK. Writing them by hand can also be buggy. Using a tool can also make it easy for making contributions like adding new ABIs.
