### ISSUE TITLE
gzip compress

### ISSUE THREAD

**Issue by ckanner** [pingcap/grpc-rs#347]
`grpc-rs` supports `Connection level compression` . And I want know whether it indicates `gzip compress` has been supported? If it was supported, you can show me some examples.

**Comment by ice1000** [comment]
https://github.com/pingcap/grpc-rs/blob/2c6dd1b2c071d20aaa9ed83f59774633f5e248c7/grpc-sys/src/lib.rs#L307-L315

**Comment by BusyJay** [comment]
Hi, @ckanner. Following is an example to build a channel with compression enabled.

https://github.com/tikv/tikv/blob/master/src/server/raft_client.rs#L51-L57

gzip is supported as well. Feel free to reopen it if you have further question.
