### ISSUE TITLE
Server keepalive configuration

### ISSUE THREAD

**Issue by Ten0** [pingcap/grpc-rs#350]
gRPC describes [here](https://github.com/grpc/grpc/blob/master/doc/keepalive.md) the keepalive configuration for both the client and the server.

I can find some options for configuring the keepalives in the ChannelBuilder (client side only, right?), but I can't find any for configuring them server-side.

How can we configure keepalive on the server side ?

**Comment by BusyJay** [comment]
ChannelBuilder can also be used to configured channel in server. Following is an example how to do it:

https://github.com/tikv/tikv/blob/master/src/server/server.rs#L106-L115
