### ISSUE TITLE
easier use duplex stream

### ISSUE THREAD

**Issue by snlansky** [pingcap/grpc-rs#359]
How to make it easier to use duplex streaming call, for example, to handle incoming and outgoing separately, without affecting each other。

**Comment by BusyJay** [comment]
I think they are separated already. You can see examples for usage.

https://github.com/pingcap/grpc-rs/blob/master/tests-and-examples/examples/route_guide/client.rs#L123-L158

**Comment by snlansky** [comment]
Is so difficult for me, I still can't write the function that handle duplex steam on the server side. can you help me?
