### ISSUE TITLE
unsafe impl `Send` for `Metadata`

### ISSUE THREAD

**Issue by Spferical** [pingcap/grpc-rs#362]
**Is your feature request related to a problem? Please describe.**
I would like to share a `grpcio::CallOption` between threads. This isn't (safely) possible at the moment because the raw pointers in it prevent Rust from deriving `Send`.

**Describe the solution you'd like**

As best I can tell, `grpcio::Metadata` owns all of its data, so it can explicitly be given `unsafe impl Send`. This would allow Rust to auto-derive `Send` for `grpcio::CallOption`.

**Describe alternatives you've considered**
Manually giving `unsafe impl Send` to types that I use that contain a `grpcio::CallOption`... Or making my own struct that gets converted into a `grpcio::CallOption` on the fly.

**Comment by BusyJay** [comment]
I don't see any problem of this. Do you want to send a PR?
