### ISSUE TITLE
Compile grpcio fail in rust:latest Docker container.

### ISSUE THREAD

**Issue by ccqpein** [pingcap/grpc-rs#364]
**Describe the bug**
Compile grpcio fail in rust:latest Docker container

**To Reproduce**
I have a project which depended on `grpcio`. In Cargo.toml: `grpcio = "0.4"`
I made a Dockerflie like:

```
FROM rust:latest

WORKDIR /temp_project

COPY . .

RUN apt-get update\
    && yes yes | apt-get install cmake \
    && cargo install --path .
```

then I try to build image `docker build`.

After all, I received error messages: 

```
-- Configuring incomplete, errors occurred!
See also "/temp_project/target/release/build/grpcio-sys-037849703dbc0a9e/out/build/CMakeFiles/CMakeOutput.log".
See also "/temp_project/target/release/build/grpcio-sys-037849703dbc0a9e/out/build/CMakeFiles/CMakeError.log".

--- stderr
CMake Warning at cmake/protobuf.cmake:48 (message):
  gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:140 (include)


CMake Error at third_party/boringssl/CMakeLists.txt:38 (message):
  Could not find Go


thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.42/src/lib.rs:861:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

**Expected behavior**
Build success.

**System information**
* CPU architecture: x86_64
* Distribution and kernel version: Linux 4.9.184-linuxkit x86_64
* SELinux on?: No?
* Any other system details we should know?:

**Additional context**
Found this issue has same error message return: 
https://github.com/pingcap/grpc-rs/issues/274#issuecomment-527506074

cmake version: 3.13.4
binutils version: 2.31.1-16
gcc version: gcc (Debian 8.3.0-6) 8.3.0

**Comment by BusyJay** [comment]
As [README](https://github.com/pingcap/grpc-rs#prerequisites) says:
> By default, the secure feature is provided by boringssl, which requires Go (>=1.7) to build. You can also use openssl instead by enabling openssl feature.

You can either install go in the docker image, use openssl or just disable the secure feature.

**Comment by ccqpein** [comment]
Thanks, let me try it tomorrow. I will let you guys update.

**Comment by Hoverbear** [comment]
I'm assuming this is resolved so I'm closing this. :)
