### ISSUE TITLE
Performance regression from v0.4.x to master

### ISSUE THREAD

**Issue by YangKeao** [pingcap/grpc-rs#376]
Benchmark with `pingcap/grpc` shows a performance regression from v0.4.x to master on some bench case. This may be related with a performance regression detected one month ago on TiKV.

Benchmark results are here, QPS(master) is the mean value of last weeks (may contain several different commits)

| Benchmark Case  | QPS(master) |QPS(v0.4.x)|
| ------------- | ------------- | ------------- |
| rust_generic_async_streaming_ping_pong  | 18244.21666666667 |19244.9|
| rust_protobuf_async_streaming_ping_pong  | 16552.416666666668  |17330.8|
| rust_protobuf_async_unary_ping_pong|10911.933333333332|11135.6|
|rust_protobuf_sync_to_async_unary_ping_pong|11178.366666666667|11259.6|
|rust_protobuf_async_unary_qps_unconstrained|187527.54999999996|192182.6|
|rust_protobuf_async_streaming_qps_unconstrained|285905.14999999997|289225.6|
|rust_protobuf_async_unary_ping_pong_1MB|185.5|170.3|

**Comment by BusyJay** [comment]
Which hash did you benchmark?
