### ISSUE TITLE
can you provide a greeter_async_client example?

### ISSUE THREAD

**Issue by nooberfsh** [pingcap/grpc-rs#68]
In c++, i can send multiple async rpc request  in a non-block way, and then in another thread,  i will get rpc result through CompletionQueue.

how can i do this with your rust grpc.

**Comment by overvenus** [comment]
Hi @nooberfsh ,

Sorry for late reply. The example is in https://github.com/pingcap/grpc-rs/blob/1b04e9c218c4ecb47d1d94391336318cce601475/examples/route_guide/client.rs.
As for the generated file, it is not included in this repo, instead, it is generated at the compile time, you can find it at `target/debug/build/grpc-proto-xxxxx/out/example/route_guide_grpc.rs` after you successful compiling the grpc-rs.

**Comment by toidiu** [comment]
wrote a standalone project using this here which might be of use https://github.com/toidiu/grcp-rs-example
