### ISSUE TITLE
Expose document of `StreamingCallSink`

### ISSUE THREAD

**Issue by hicqu** [pingcap/grpc-rs#89]
According to [official doc site](https://docs.rs/grpcio/0.1.0/grpcio/type.ClientCStreamSender.html), there is no document about `StreamingCallSink`.
After check the source code, I know it's a implemention of `futures::stream::Sink`.
So do you think expose this into document is a good idea? @BusyJay  If so, I can do this.

**Comment by BusyJay** [comment]
Sure, do it please.

**Comment by hicqu** [comment]
Fixed.
