### ISSUE TITLE
grpc-rs fails to build on ppc64le

### ISSUE THREAD

**Issue by seth-priya** [pingcap/grpc-rs#90]
This is related to https://github.com/pingcap/tikv/issues/1965 and part of the overall effort to port tikv to ppc64le.

The specific issue here is due to the dependency on a older version of grpc, that comes from
https://github.com/pingcap/grpc

This version of grpc is not supported on ppc64le, while the current master https://github.com/grpc/grpc actually works on ppc64le (builds and passes its self-tests).  grpc-rs builds fine even on ppc64le, after updating it to point to https://github.com/grpc/grpc and I was successfully able to use that build with tikv. However, this was a temporary workaround.

I would like to understand the requirements to fix this issue upstream. Towards, that end, I had a few queries:
1 - Is there a specific reason for using a fork of a specific version of grpc, rather than mainstream grpc? and would it make it challenging to keep up with the changes happening on grpc in the longer term? Do we plan to switch to using grpc up-stream at some point?
2 - Would it be acceptable if we attempt to update grpc to the latest master? I understand that there are certain commits in the forked repo, that may not be present in the up-stream grpc repo and am not sure how challenging integration might be.
3 - I would like to understand, if, apart from 1 and 2, there is a better/recommended way to handle the issue?

Thanks!

Regards,
Priya

**Comment by BusyJay** [comment]
Mater branch of gRPC is not stable enough for production usage, we would like to only stick to the release version.

And unfortunately the release version of gRPC doesn't always build with cmake. So our fork contains several patches that just make it working. We did send the patches to upstream too, though they are either not merged or not included into any releases yet.

We have switched gRPC to v1.6.1 in master branch, does it work on ppc64le? A new version will be released after we finished some benchmarks.

**Comment by seth-priya** [comment]
@BusyJay, thanks for the quick response and explaining the situation in detail.

Sorry, I complete missed that last commit - that fixes my problem. I am able to build grpc-rs on ppc64le now. All tests are passing as well.

So, I believe that the new release of grpcio will integrate well with tikv on ppc64le - thanks!

Closing this issue.
